server:
  port: 8810
  servlet:
    context-path: /order-server

#指定当前服务的名称
spring:
  application:
    name: cloud-order

#  指定 服务注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8801/eureka
